- name: "SCORED | 3.3.2 | Ensure IPv6 redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  when: rhel7gsa_ipv6_required == true
  tags:
      - sysctl
      - id_3.3.2

- name: "UNSCORED | 3.3.3 | Ensure IPv6 is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      line: "options ipv6 disable=1"
      create: present
  when: rhel7gsa_ipv6_required == false
  tags:
      - id_3.3.3
