- name: "SCORED | 4 | Ensure lockout for failed password attempts is configured; password-auth"
  template:
    src: audit_rules
    dest: /etc/audit/rules.d/audit.rules
  tags:
      - id_5.3.2
      - id_5.3.3
      - id_5.3.4
