- name: 2.2.8-2.2.14 | Ensure DNS,FTP,HTTP,IMAP,POP,Samba,Proxy,SNMP Servers are not enabled (Not Scored)
  service: >
      name={{ item }}
      enabled=no
  with_items:
    - cups
    - bind9
    - vsftpd
    - apache2
    - dovecot
    - smbd
    - squid3
    - snmpd
  failed_when: False
  tags:
    - id_2.2.8-2.2.14
