- name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted"
  lineinfile:
      state: present
      dest: /etc/pam.d/su
      regexp: '^#auth\s+required\s+pam_wheel\.so'
      line: 'auth           required        pam_wheel.so use_uid'
