- name: "SCORED | 5.6 | Ensure access to the su command is restricted"
  lineinfile:
    dest: /etc/pam.d/su
    state: present
    regexp: '^auth           required        pam_wheel.so use_uid'
    line: 'auth           required        pam_wheel.so use_uid'
    backrefs: yes
    state: present
  tags:
      - id_5.6
