- name: "PRELIM | List users accounts"
  command: "awk -F':' '/wheel/{print $4}' /etc/group"
  register: wheel_users
  changed_when: no
  check_mode: no

- name: "Testing Blcokinfile"
  blockinfile:
    path: /etc/group
    block: wheel:x:10:root,{{ item }}
  with_items:
    - {{ wheel_users.stdout }}


#- name: "Testing appedning wheel:x:"
#  debug: msg="{{ item }}"
#  with_items:
#    - "{{ wheel_users.stdout }}"

- name: "5.6 | Ensure access to the su command is restricted"
  lineinfile:
    dest: /etc/group
    regexp: '^wheel:x:10:'
    line: wheel:x:10:{{ item }}
    #backrefs: true
    state: present
  with_items:
    - "root,{{ wheel_users.stdout }}"
  when: wheel_users.stdout == 'root'
  tags:
      - id_5.6

- name: "Testing appedning wheel:x:"
  debug: msg='{{ item }}'
  with_items:
    - "{{ wheel_users.stdout }}"
  when: root_grp_status.stdout == ""

- name: "5.6 | Ensure access to the su command is restricted"
  lineinfile:
    dest: /etc/group
    regexp: '^wheel:x:10:'
    line: wheel:x:10:root,{{ item }}
    #backrefs: true
    state: present
  with_items:
    - "{{ wheel_users.stdout }}"
  when: root_grp_status == ""
  tags:
   - id_5.6
