- name: 10.5.1 Lock Inactive User Accounts (check) (Scored)
  command: grep INACTIVE /etc/login.defs
  changed_when: False
  failed_when: False
  always_run: True
  register: lock_inactive_rc
  tags:
    - section10
    - section10.5

- name: 10.5.2 Lock Inactive User Accounts (Scored)
  lineinfile: >
      dest=/etc/login.defs
      line='INACTIVE=35'
      state=present
  when: lock_inactive_rc.rc == 1
  tags:
    - section10
    - section10.5   
