- name: "SCORED | 5.3.2-5.3.3 | Ensure lockout for failed password attempts is configured; password-auth"
  template:
    src: password-auth
    dest: /etc/pam.d/password-auth
  tags:
      - id_5.3.2
      - id_5.3.3

- name: "SCORED | 5.3.2-5.3.3 | Ensure lockout for failed password attempts is configured; password-auth"
  template:
    src: system-auth
    dest: /etc/pam.d/system-auth
  tags:
      - id_5.3.2
      - id_5.3.3
