- name: "SCORED | 5.4.1.4 | Lock Inactive User Accounts"
  lineinfile:
      state: present
      dest: /etc/default/useradd
      regexp: '^INACTIVE'
      line: 'INACTIVE=35'
      state=present
  tags:
    -  id_5.4.1.4
